-- begin MIMISMART_ORDER_FROM_SUPPLIER
alter table MIMISMART_ORDER_FROM_SUPPLIER add constraint FK_MIMISMART_ORDER_FROM_SUPPLIER_ON_SUPPLIER foreign key (SUPPLIER_ID) references MIMISMART_SUPPLIER(ID)^
alter table MIMISMART_ORDER_FROM_SUPPLIER add constraint FK_MIMISMART_ORDER_FROM_SUPPLIER_ON_STATUS foreign key (STATUS_ID) references MIMISMART_ORDER_STATUS(ID)^
create index IDX_MIMISMART_ORDER_FROM_SUPPLIER_ON_SUPPLIER on MIMISMART_ORDER_FROM_SUPPLIER (SUPPLIER_ID)^
create index IDX_MIMISMART_ORDER_FROM_SUPPLIER_ON_STATUS on MIMISMART_ORDER_FROM_SUPPLIER (STATUS_ID)^
-- end MIMISMART_ORDER_FROM_SUPPLIER

-- begin MIMISMART_NOMENCLATURE
alter table MIMISMART_NOMENCLATURE add constraint FK_MIMISMART_NOMENCLATURE_ON_UNIT foreign key (UNIT_ID) references MIMISMART_UNITS(ID)^
alter table MIMISMART_NOMENCLATURE add constraint FK_MIMISMART_NOMENCLATURE_ON_ORDER_FROM_SUPPLIER foreign key (ORDER_FROM_SUPPLIER_ID) references MIMISMART_ORDER_FROM_SUPPLIER(ID)^
create index IDX_MIMISMART_NOMENCLATURE_ON_UNIT on MIMISMART_NOMENCLATURE (UNIT_ID)^
create index IDX_MIMISMART_NOMENCLATURE_ON_ORDER_FROM_SUPPLIER on MIMISMART_NOMENCLATURE (ORDER_FROM_SUPPLIER_ID)^
-- end MIMISMART_NOMENCLATURE
-- begin MIMISMART_ORDER_LINE
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_NAME foreign key (NAME_ID) references MIMISMART_NOMENCLATURE(ID)^
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_UNITS foreign key (UNITS_ID) references MIMISMART_UNITS(ID)^
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_ORDER_FROM_SUPPLIER foreign key (ORDER_FROM_SUPPLIER_ID) references MIMISMART_ORDER_FROM_SUPPLIER(ID)^
create index IDX_MIMISMART_ORDER_LINE_ON_NAME on MIMISMART_ORDER_LINE (NAME_ID)^
create index IDX_MIMISMART_ORDER_LINE_ON_UNITS on MIMISMART_ORDER_LINE (UNITS_ID)^
create index IDX_MIMISMART_ORDER_LINE_ON_ORDER_FROM_SUPPLIER on MIMISMART_ORDER_LINE (ORDER_FROM_SUPPLIER_ID)^
-- end MIMISMART_ORDER_LINE
