alter table MIMISMART_NOMENCLATURE rename to MIMISMART_NOMENCLATURE__U98224 ;
alter table MIMISMART_UNITS drop constraint FK_MIMISMART_UNITS_ON_NOMENCLATURE ;
alter table MIMISMART_ORDERS drop constraint FK_MIMISMART_ORDERS_ON_NAME ;
alter table MIMISMART_ORDERS drop constraint FK_MIMISMART_ORDERS_ON_UNITS ;
