alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references MIMISMART_ORDER_FROM_SUPPLIER(ID);
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_NOMENKLATURA foreign key (NOMENKLATURA_ID) references MIMISMART_NOMENCLATURE(ID);
create index IDX_MIMISMART_ORDER_LINE_ON_ORDER on MIMISMART_ORDER_LINE (ORDER_ID);
create index IDX_MIMISMART_ORDER_LINE_ON_NOMENKLATURA on MIMISMART_ORDER_LINE (NOMENKLATURA_ID);
