alter table MIMISMART_NOMENCLATURE add constraint FK_MIMISMART_NOMENCLATURE_ON_UNIT foreign key (UNIT_ID) references MIMISMART_UNITS(ID);
create index IDX_MIMISMART_NOMENCLATURE_ON_UNIT on MIMISMART_NOMENCLATURE (UNIT_ID);
