alter table MIMISMART_ORDERS add constraint FK_MIMISMART_ORDERS_ON_NAME foreign key (NAME_ID) references MIMISMART_NOMENCLATURE(ID);
alter table MIMISMART_ORDERS add constraint FK_MIMISMART_ORDERS_ON_UNITS foreign key (UNITS_ID) references MIMISMART_NOMENCLATURE(ID);
create index IDX_MIMISMART_ORDERS_ON_NAME on MIMISMART_ORDERS (NAME_ID);
create index IDX_MIMISMART_ORDERS_ON_UNITS on MIMISMART_ORDERS (UNITS_ID);
