alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_UNITS foreign key (UNITS_ID) references MIMISMART_UNITS(ID);
create index IDX_MIMISMART_ORDER_LINE_ON_UNITS on MIMISMART_ORDER_LINE (UNITS_ID);
