alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_NAME foreign key (NAME_ID) references MIMISMART_NOMENCLATURE(ID);
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_UNITS foreign key (UNITS_ID) references MIMISMART_UNITS(ID);
alter table MIMISMART_ORDER_LINE add constraint FK_MIMISMART_ORDER_LINE_ON_ORDER_FROM_SUPPLIER foreign key (ORDER_FROM_SUPPLIER_ID) references MIMISMART_ORDER_FROM_SUPPLIER(ID);
create index IDX_MIMISMART_ORDER_LINE_ON_NAME on MIMISMART_ORDER_LINE (NAME_ID);
create index IDX_MIMISMART_ORDER_LINE_ON_UNITS on MIMISMART_ORDER_LINE (UNITS_ID);
create index IDX_MIMISMART_ORDER_LINE_ON_ORDER_FROM_SUPPLIER on MIMISMART_ORDER_LINE (ORDER_FROM_SUPPLIER_ID);
